id = "grey-theme"
name = "Grey Theme"
version = "0.1.0"
description = "Light. Minimal. Grey."
schema_version = 1
authors = ["Marco Garcia <mvrcoag@gmail.com>"]
repository = "https://github.com/mvrcoag/zed-grey-theme"
